export const graphics = {
  logoDark: '/assets/graphics/04_logo_brand/divedrop_logo_full_dark.png',
  logoWhite: '/assets/graphics/04_logo_brand/divedrop_logo_full_white.png',
  wordmarkDark: '/assets/graphics/04_logo_brand/divedrop_wordmark_dark.png',
  iconDark: '/assets/graphics/04_logo_brand/divedrop_icon_dark.png',
  heroMain: '/assets/graphics/01_backgrounds_web/hero_underwater_split_1920x1080_text_safe.png',
  heroMainMobile: '/assets/graphics/02_backgrounds_mobile/hero_underwater_split_1080x1920.png',
  heroInstructor: '/assets/graphics/01_backgrounds_web/divers_boat_sunset_1920x1080_text_safe.png',
  heroInstructorMobile: '/assets/graphics/02_backgrounds_mobile/divers_boat_sunset_1080x1920.png',
  heroPremium: '/assets/graphics/01_backgrounds_web/premium_marker_submarine_1920x1080_text_safe.png',
  heroPremiumMobile: '/assets/graphics/02_backgrounds_mobile/hero_underwater_split_1080x1920.png',
  waterline: '/assets/graphics/03_transparent_png/waterline_wave_overlay_transparent.png',
  underwaterOverlay: '/assets/graphics/03_transparent_png/underwater_scene_overlay_transparent.png',
  reefOverlay: '/assets/graphics/03_transparent_png/coral_reef_bottom_overlay_transparent.png',
  shuttleVan: '/assets/graphics/03_transparent_png/divedrop_shuttle_van_transparent.png',
  redShuttle: '/assets/graphics/03_transparent_png/red_shuttle_reference_softcut.png',
  scubaDiver: '/assets/graphics/03_transparent_png/scuba_diver_softcut_transparent.png',
  diveBoat: '/assets/graphics/03_transparent_png/dive_boat_transparent.png',
  diversOnBoat: '/assets/graphics/03_transparent_png/divers_on_boat_foreground_softcut.png',
  tower: '/assets/graphics/03_transparent_png/eilat_observation_tower_transparent.png',
  palm: '/assets/graphics/03_transparent_png/palm_tree_softcut.png',
  submarine: '/assets/graphics/03_transparent_png/yellow_submarine_softcut_transparent.png',
  interfaceKit: '/assets/graphics/08_interface_kit/divedrop_interface_kit_board_1440x1600.png',
  instructorExplainer: '/assets/graphics/07_instructor_explainer/instructor_invite_explainer_1080x1350.png',
  instructorStory: '/assets/graphics/07_instructor_explainer/instructor_invite_story_1080x1920.png',
  uiFlow: '/assets/graphics/09_transparent_ui_components/flow_dive_shuttle_guide_transparent.png',
  uiBottomNav: '/assets/graphics/09_transparent_ui_components/mobile_bottom_nav_transparent.png',
  uiDiveCard: '/assets/graphics/09_transparent_ui_components/card_dive_site_transparent.png',
  uiInstructorCard: '/assets/graphics/09_transparent_ui_components/card_instructor_available_transparent.png',
};

export type GraphicsKey = keyof typeof graphics;
