-- Seed dive_sites table with 5 popular dive destinations

INSERT INTO dive_sites (
  name,
  description,
  country,
  region,
  location_latitude,
  location_longitude,
  address,
  difficulty_level,
  max_depth_recommended,
  average_depth,
  water_temperature_summer,
  water_temperature_winter,
  visibility_average,
  water_type,
  marine_life,
  notable_features,
  access_type,
  entry_fee,
  accessibility_rating,
  best_season_start,
  best_season_end,
  currents_rating,
  suitability_beginner,
  suitability_intermediate,
  suitability_advanced,
  facilities,
  nearby_services,
  emergency_facilities,
  decompression_required,
  night_diving_available,
  wreck_diving,
  cave_diving,
  wall_diving,
  coral_rating,
  avg_rating,
  review_count,
  hazard_notes,
  special_instructions
) VALUES
(
  'Great Barrier Reef - Coral Sea',
  'World''s largest coral reef system with incredible biodiversity and pristine coral gardens. Perfect for exploring vibrant fish species and healthy coral formations.',
  'Australia',
  'Queensland',
  -16.2859,
  145.7781,
  'Cairns, Queensland',
  'intermediate',
  40,
  25,
  28,
  23,
  30,
  'saltwater',
  ARRAY['clownfish', 'grouper', 'sea turtle', 'reef shark', 'parrotfish', 'angelfish'],
  ARRAY['pristine coral gardens', 'abundant marine life', 'world-famous reef', 'clear water', 'tropical atmosphere'],
  'boat',
  150.00,
  4,
  5,
  10,
  2,
  true,
  true,
  true,
  ARRAY['dive shop', 'restaurant', 'accommodation', 'dive briefing center'],
  ARRAY['hospital', 'airport', 'shops', 'bars'],
  true,
  false,
  true,
  true,
  false,
  false,
  5,
  4.8,
  856,
  'Strong currents possible on exposed reefs. Monitor air consumption closely.',
  'Bring reef-safe sunscreen. Multiple dive sites available within the reef system.'
),
(
  'Blue Hole - Belize',
  'A spectacular submarine sinkhole with dramatic walls dropping to 124 meters. Famous for its unique geological formation and schools of reef sharks.',
  'Belize',
  'Lighthouse Reef Atoll',
  17.3168,
  -87.5401,
  'Lighthouse Reef Atoll, Belize City',
  'advanced',
  45,
  30,
  28,
  24,
  20,
  'saltwater',
  ARRAY['reef shark', 'grouper', 'tarpon', 'spotted eagle ray', 'nurse shark'],
  ARRAY['dramatic sinkhole', 'limestone formations', 'shark encounters', 'steep walls', 'unique geology'],
  'boat',
  200.00,
  3,
  4,
  11,
  3,
  false,
  true,
  true,
  ARRAY['dive shop', 'resort'],
  ARRAY['airport', 'accommodation'],
  false,
  true,
  false,
  false,
  false,
  true,
  4,
  4.7,
  423,
  'Very deep dive with decompression requirements. Strong currents. Advanced certification required.',
  'This is a bucket list dive. Descent into the blue void is spectacular. Plan for multiple dives in the area.'
),
(
  'Palau - Peleliu Corner',
  'Stunning wall dive with incredible diversity of marine life. Clear waters, abundant fish schools, and world-class coral health make this a premier diving destination.',
  'Palau',
  'Peleliu',
  7.3333,
  134.4833,
  'Peleliu, Palau',
  'intermediate',
  35,
  22,
  29,
  27,
  35,
  'saltwater',
  ARRAY['bumphead parrotfish', 'trevally', 'barracuda', 'sea turtle', 'manta ray', 'shark', 'sweetlips'],
  ARRAY['healthy coral walls', 'fast currents with rich fish life', 'big pelagics', 'schooling fish', 'pristine environment'],
  'boat',
  75.00,
  5,
  11,
  4,
  3,
  true,
  true,
  true,
  ARRAY['dive shop', 'resort', 'restaurant'],
  ARRAY['accommodation', 'shops', 'airport'],
  true,
  false,
  false,
  false,
  false,
  true,
  5,
  4.9,
  612,
  'Current can be strong. Check weather and conditions before diving. Surge possible on exposed walls.',
  'Palau is a top-tier diving destination. Multiple world-class sites in the area. Respect local marine protection regulations.'
),
(
  'Red Sea - Ras Muhammad',
  'Iconic Egyptian dive site with dramatic pinnacles, pristine coral gardens, and abundant tropical fish. Excellent visibility and rich marine ecosystem.',
  'Egypt',
  'Sinai Peninsula',
  27.7283,
  34.2733,
  'Ras Muhammad National Park, Sharm El-Sheikh',
  'beginner',
  30,
  18,
  29,
  21,
  25,
  'saltwater',
  ARRAY['angelfish', 'butterflyfish', 'grouper', 'moray eel', 'sea turtle', 'barracuda', 'snapper'],
  ARRAY['coral pinnacles', 'healthy coral gardens', 'colorful fish', 'dramatic topography', 'clear warm water'],
  'boat',
  40.00,
  5,
  3,
  11,
  2,
  true,
  true,
  true,
  ARRAY['dive shop', 'resort', 'restaurant', 'beach club'],
  ARRAY['hospital', 'shops', 'accommodation', 'airport'],
  true,
  false,
  true,
  false,
  false,
  false,
  5,
  4.6,
  934,
  'Occasional surge in strong wind conditions. Protected national park - fishing prohibited.',
  'One of Egypt''s best dive sites. Perfect for underwater photography. Respect marine protection zones.'
),
(
  'Bonaire - House Reef',
  'A shore-accessible reef system ideal for beginners and photography enthusiasts. Incredible biodiversity, excellent visibility, and no boat required.',
  'Bonaire',
  'Caribbean',
  12.1696,
  -68.2524,
  'Bonaire National Marine Park',
  'beginner',
  20,
  12,
  27,
  25,
  25,
  'saltwater',
  ARRAY['parrotfish', 'wrasse', 'damselfish', 'pufferfish', 'lionfish', 'seahorse', 'conch'],
  ARRAY['shore accessible', 'vibrant reef life', 'excellent for macro photography', 'protected marine park', 'consistent conditions'],
  'shore',
  25.00,
  5,
  6,
  11,
  1,
  true,
  true,
  true,
  ARRAY['dive shop', 'resort', 'restaurant', 'shop'],
  ARRAY['accommodation', 'airport', 'hospital', 'shops'],
  true,
  false,
  false,
  false,
  false,
  false,
  4,
  4.5,
  687,
  'Sea urchins present. Watch where you step. Lionfish spotted - do not handle.',
  'Perfect location for learning and photography. Buddy system required. Park entry fee included.'
);
